kind: Namespace
apiVersion: v1
metadata:
  name: captain-system

---

# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: captain-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: captain-server
  namespace: captain-system

---

# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: captain-server
  namespace: captain-system

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: captain-config
  namespace: captain-system
data:
  captain.yaml: |-
    multicluster:
      enable: true

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: captain-server
  name: captain-server
  namespace: captain-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captain-server
  template:
    metadata:
      labels:
        app: captain-server
    spec:
      volumes:
        - name: captain-config
          configMap:
            name: captain-config
            defaultMode: 420
      containers:
      - image: cgdeeplearn/captain-server:latest
        name: captain-server
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: captain-config
            mountPath: /etc/captain/
      serviceAccountName: captain-server

---

# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: captain-server
  name: captain-server
  namespace: captain-system
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: captain-server
